### ISSUE TITLE
Change gradients to solid colors for sponsor blocks on homepage

### ISSUE THREAD

**Issue by hussainweb** [drupal-bangalore/drupalcamp-bangalore#11]
The gradients look a bit awkward and don't go well with the rest of the site. I suggest changing them to solid colors. I did a preview and it looks somewhat better. We would also change the font and image sizing to match the diamond block.

**Comment by ssudhak** [comment]
Can you update this in staging server, lets see how it looks

**Comment by ramrudra** [comment]
Any specific colors or remove the gradients entirely?

**Comment by hussainweb** [comment]
I tried in DOM inspector to fill it with the gradient start color and the gold block looked just okay but the silver block looked fine. I think we could tweak the color a bit for the gold block (maybe to match the register button).
