### ISSUE TITLE
Remove all the extra Sponsor buttons

### ISSUE THREAD

**Issue by hussainweb** [drupal-bangalore/drupalcamp-bangalore#13]
In Gold and Silver sponsorship blocks, there are many "Become a sponsor" buttons. I think it's time to take them out and have just one. Thoughts?

**Comment by ssudhak** [comment]
Yes, we can do that, i was thinking of it from some time. i have changed it now in the staging server. please check

**Comment by hussainweb** [comment]
Let's do this on live after we push all our recent changes.
