### ISSUE TITLE
People those who have submitted sessions cannot edit their own sessions.

### ISSUE THREAD

**Issue by nkgokul** [drupal-bangalore/drupalcamp-bangalore#5]
People those who have submitted sessions cannot edit their own sessions. It should just be a permission change, I think.

**Comment by nkgokul** [comment]
Edit button/tab is not visible. 
![screenshot from 2015-07-06 13 08 48](https://cloud.githubusercontent.com/assets/1375897/8517693/cfff117a-23e0-11e5-921a-46ea9833f2f7.png)

**Comment by hussainweb** [comment]
I just fixed the permissions and rebuilt them. Please try once more.

**Comment by nkgokul** [comment]
Confirmed that this works now.
