### ISSUE TITLE
Redirect anonymous user  willing to submit a session to login page.

### ISSUE THREAD

**Issue by taher-pro** [drupal-bangalore/drupalcamp-bangalore#9]
Currently when an anonymous user goes to /node/add/session an access denied message is shown. The Anonymous user needs to be redirected to login page.

**Comment by ssudhak** [comment]
added access denied page with sign in link

**Comment by hussainweb** [comment]
Reopening as there is an alternative in works.

**Comment by hussainweb** [comment]
Will be closed once 85defa3 is in live and configured.

**Comment by hussainweb** [comment]
This has been configured on live and working.
